notifications:
  email: false
git:
  depth: 2
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    language: python
    python: '2.7'
    env: CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
  - os: linux
    dist: trusty
    sudo: required
    language: python
    python: '2.7'
    env: CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
      BUILD_SUITESPARSE=1 COVERALLS=1
  - os: linux
    dist: trusty
    sudo: required
    language: python
    python: '3.5'
    env: CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
  - os: linux
    dist: trusty
    sudo: required
    language: python
    python: '3.6'
    env: CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
  - os: osx
    env: PYVERSION=2.7 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=0 CVXOPT_BUILD_FFTW=1
      CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas
      CVXOPT_LAPACK_LIB=openblas BUILD_SUITESPARSE=1
    language: generic
  - os: osx
    env: PYVERSION=2.7 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=0 CVXOPT_BUILD_FFTW=1
      CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas
      CVXOPT_LAPACK_LIB=openblas
    language: generic
  - os: osx
    env: PYVERSION=3.6 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=0 CVXOPT_BUILD_FFTW=1
      CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas
      CVXOPT_LAPACK_LIB=openblas
    language: generic
before_install:
- if [[ "$BUILD_SUITESPARSE" == "1" ]]; then wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.4.tar.gz; tar -xf SuiteSparse-4.5.4.tar.gz; export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev libopenblas-dev libfftw3-dev libglpk-dev libdsdp-dev libgsl0-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && -z "$BUILD_SUITESPARSE" ]]; then sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687 -y; sudo apt-get update; sudo apt-get install libsuitesparse-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openblas glpk gsl fftw; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" && -z "$BUILD_SUITESPARSE" ]]; then brew install suite-sparse; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "2.7" ]]; then virtualenv venv -p python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "3.6" ]]; then brew install python3; virtualenv venv -p python3; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
- pip install coveralls nose
- python setup.py install
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -c 'from cvxopt import blas,lapack,glpk,fftw,dsdp,gsl,cholmod,umfpack'; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -c 'from cvxopt import blas,lapack,glpk,fftw,gsl,cholmod,umfpack'; fi
- nosetests --with-coverage --cover-package=cvxopt
after_success:
- if [ $COVERALLS ]; then coveralls; fi
